remote_theme: coursweb/jk-theme
title: Newsletters
description: Sous-module pour cours-web.ch, sur la conception de newsletters.
lang: fr-FR
chapters:
 - title: Cours-web
   url: https://cours-web.ch/
 - title: Email
   url: https://cours-web.ch/email/
 - title: Bases en informatique
   url: https://cours-web.ch/informatique-base/   
# Footer content
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Un support de cours</li>  
  <li>Eracom, Lausanne</li>
  <li>2022</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/coursweb/newsletters">Lien Github</a></li></ul>
